import { Calendar, Shield, Eye, Lock, Globe, FileText } from "lucide-react";

export const metadata = {
  title: "Privacy Policy | Aura",
  description: "Read the Aura Privacy Policy. Learn about our data collection practices, user rights, and security standards.",
};

export default function PrivacyPage() {
  return (
    <div className="space-y-8 max-w-3xl mx-auto">
      {/* Page Title */}
      <div className="space-y-3 border-b border-border pb-6">
        <h1 className="text-3xl font-extrabold tracking-tight">Privacy Policy</h1>
        <div className="flex items-center gap-2 text-xs text-muted-foreground">
          <Calendar className="h-3.5 w-3.5" />
          <span>Last Updated: June 3, 2026</span>
        </div>
      </div>

      <p className="text-sm text-muted-foreground leading-relaxed">
        Aura ("we," "our," or "us") operates the website located at <a href="https://aura-beam.vercel.app" className="text-primary hover:underline">https://aura-beam.vercel.app</a> (the "Service"). This Privacy Policy informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.
      </p>

      {/* Policy Content */}
      <div className="space-y-8 text-sm text-muted-foreground leading-relaxed">
        <section className="space-y-3">
          <h2 className="text-lg font-bold text-foreground">1. Definitions</h2>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>Personal Data:</strong> Data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</li>
            <li><strong>Usage Data:</strong> Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
            <li><strong>Cookies:</strong> Small files stored on your device (computer or mobile device).</li>
            <li><strong>Data Controller:</strong> The natural or legal person who determines the purposes for which and the manner in which any personal information is processed. For this Service, we are the Data Controller of your Personal Data.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-foreground">2. Information Collection and Use</h2>
          <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
          
          <h3 className="text-sm font-semibold text-foreground mt-4">Types of Data Collected:</h3>
          <div className="space-y-3 pl-4 border-l-2 border-border">
            <p><strong>A. Personal Data</strong></p>
            <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Profile picture and OAuth identification tokens (via Google or other OAuth providers)</li>
              <li>Card scanning files and collection portfolio metadata</li>
            </ul>

            <p className="mt-4"><strong>B. Usage Data</strong></p>
            <p>We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
          </div>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-foreground">3. Image & Scanning Uploads</h2>
          <p>
            Our Service offers an AI-powered trading card scanner. When you upload or capture an image of a trading card:
          </p>
          <ul className="list-disc pl-5 space-y-2">
            <li>The image file is temporarily processed by our servers and AI recognition partner APIs (such as OpenAI's Vision APIs) to match the card details.</li>
            <li>If you choose to save the card to your collection, the image preview metadata is preserved securely within our storage solution (AWS S3) to display your collection binder.</li>
            <li>If you do not save the card, the image is discarded immediately after analysis. You may delete any of your saved cards and associated scan images at any time.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-foreground">4. Use of Data</h2>
          <p>Aura uses the collected data for various purposes:</p>
          <ul className="list-disc pl-5 space-y-2">
            <li>To provide and maintain our Service (including database replication and collection tracking)</li>
            <li>To notify you about changes to our Service</li>
            <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
            <li>To provide customer support and gather analysis to improve the Service</li>
            <li>To monitor the usage of our Service and detect, prevent, and address technical issues</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-foreground">5. GDPR & CCPA Compliance (Data Protection Rights)</h2>
          <p>
            If you are a resident of the European Economic Area (EEA) or California, you have certain data protection rights. Aura aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
          </p>
          <p>Under certain circumstances, you have the following data protection rights:</p>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>The right to access:</strong> You can request copies of your personal data.</li>
            <li><strong>The right to rectification:</strong> You can request that we correct any information you believe is inaccurate.</li>
            <li><strong>The right to erasure ("Right to be Forgotten"):</strong> You can request that we erase your personal data under certain conditions.</li>
            <li><strong>The right to restrict processing:</strong> You can request that we restrict the processing of your personal data.</li>
            <li><strong>The right to data portability:</strong> You have the right to be provided with a copy of the information we have on you in a structured, machine-readable format.</li>
            <li><strong>The right to withdraw consent:</strong> You also have the right to withdraw your consent at any time where Aura relied on your consent to process your personal information.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-foreground">6. Service Providers & Third-Party Sharing</h2>
          <p>
            We may employ third-party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, or to assist us in analyzing how our Service is used. These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
          </p>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>Hosting:</strong> Vercel (Frontend) and Render (Backend API).</li>
            <li><strong>Database:</strong> Supabase (PostgreSQL storage).</li>
            <li><strong>APIs & AI Models:</strong> OpenAI (Vision analysis), TCGPlayer API, and YGOPRODeck / Pokemon TCG SDKs (pricing and card metadata).</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-lg font-bold text-foreground">7. Changes to This Privacy Policy</h2>
          <p>
            We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last Updated" date at the top of this Privacy Policy.
          </p>
        </section>
      </div>
    </div>
  );
}
